apiVersion: apps/v1
kind: Deployment
metadata:
  name: matching-engine
  labels:
    app: matching-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matching-engine
  template:
    metadata:
      labels:
        app: matching-engine
    spec:
      containers:
      - name: matching-engine
        image: matching-engine:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 50051
        env:
        - name: TRADING_PAIR
          value: "BTC/USD"
