apiVersion: v1
kind: Service
metadata:
  name: order-gateway
  labels:
    app: order-gateway
spec:
  selector:
    app: order-gateway
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30080
  type: NodePort
